// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqTQi3z8J3zp1VeGN5m6Eeorf6w6Q80zo',
    appId: '1:211615536526:web:0ae301bd58aedbef3d80df',
    messagingSenderId: '211615536526',
    projectId: 'truechatapp-35bd3',
    authDomain: 'truechatapp-35bd3.firebaseapp.com',
    storageBucket: 'truechatapp-35bd3.appspot.com',
    measurementId: 'G-TGDRTSXG60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUQ0Fl-DxlluBYYZ2UD3QVDakVDr5XZn0',
    appId: '1:211615536526:android:64b8f38970eb36e73d80df',
    messagingSenderId: '211615536526',
    projectId: 'truechatapp-35bd3',
    storageBucket: 'truechatapp-35bd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaUoS2aPmCapx4Sgwb30rRyD0ZBesxCnw',
    appId: '1:211615536526:ios:5caaa916846d10a23d80df',
    messagingSenderId: '211615536526',
    projectId: 'truechatapp-35bd3',
    storageBucket: 'truechatapp-35bd3.appspot.com',
    iosBundleId: 'com.example.trueChatApp',
  );
}
